import 'package:flutter/material.dart';
import 'package:workify/utils/sizes.dart';

late final ip;
late final port;
const kPrimaryColor = Color(0xFF1976d2);
const kSecondaryColor = Color(0xFFF5F6FC);
const kMenuColor = Color(0xFFF2F4FC);
const kMenuDarkColor = Color(0xff212734);
const kScaffoldColor = Color(0xFFEBEDFA);
const kScaffoldDarkColor = Color(0xff394253);
const kBadgeColor = Color(0xFFEE376E);
const kGrayColor = Color(0xFF8793B2);
const kTitleTextColor = Color(0xFF30384D);
const kTextColor = Color(0xFF4D5875);
const kTextDarkColor = Color(0xFFDFE2EF);
const kDefaultPadding = 20.0;
const kDividerColor = Color(0xFFDFE2EF);
const kDividerDarkColor = Colors.white24;
const kBottomShadowColorDark = Color(0xff485063);
const kTopShadowColorDark = Color(0xff262C37);
const kTopShadowColor = Colors.white60;
const kBottomShadowColor = Color(0x26234395);
const kWhaleColor = Color(0xff190e8f);
const double bannerHeight = 84;
